export const VENDORS = [
  'Bob\'s Burgers',
  'Krusty Burger',
  'McBurgerTown',
  'Arnie\'s Sarnies',
  'Mando\'s',
  'Pret a Composter',
  'Wild West Wings',
  'Avocadno\'s',
  'Stu\'s Stews',
  'Tame Chef',
  'Lizzi',
  'Pizza the Hutt',
  'Gnomesbake',
  'Patty and Pun',
  'Uncle Moe’s Family Feedbag',
  'JUMP Vietnamese',
  'Los Pollos Hermanos',
  'Pizza Planet',
  'Hummus Sisters',
  'Coco di Papa',
  'Benito\'s Cat',
  'Uncle Paul\'s Austrian Pantry',
  'The Pie Hole',
  'Big Kahuna Burger',
  'The Leaky Cauldron',
  'Weasleys\' Wizard Wheezes',
  'Duff Breweries',
];
